version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - testing-network      

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - testing-network


networks:
  testing-network:
    external: true      